# -*- coding:utf-8 -*-
{
    'name': 'Avancys ERP Modulos',
    'version': '1.0',
    'depends': [
        'base',
        'contacts',
        'mail',
        'product',
        'purchase',
        'account',
        'sale_management',
        'crm',
        'account',
        'hr',
        'hr_recruitment',
        'fleet',
        'hr_contract',
        'website_hr_recruitment',
        'board',
        'note',
        'lunch',
        'hr_skills',
        'hr_holidays',
        'hr_attendance',
        'survey',
        'website_event',
        'mass_mailing',
        'website_sale',
        'website_slides',
        'im_livechat',
        'maintenance',
        'point_of_sale',
        'website_blog',
        'repair',
        'website_forum',
    ],
    'author': 'Vise Ltda',
    'category': 'Avancys Modelos',
    'website': 'www.google.com',
    'summary': 'Modulo de modelos avancys',
    'description': '''
    Modulo para homologar avancys
    ''',
    'data': [
        'security/ir.model.access.csv',
        'data/ir_model_data.xml',
            'views/purchase_requisition_menu.xml'
    ],
}

